# Generated by Django 3.2.7 on 2021-12-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malivhu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('posted', models.DateTimeField()),
            ],
            options={
                'ordering': ['posted'],
            },
        ),
    ]
